my_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: RLOXBWF-OY38954
      user: GUILHERME
      role: ACCOUNTADMIN
      database: DBT_TEST
      warehouse: COMPUTE_WH
      schema: DATAWAREHOUSE
      password: Cienciadedados1@



